"""Compiled numeric kernels: the one Numba policy of the engine (PH4a; no model semantics).

Kernels reproduce frozen Python/numpy arithmetic exactly (Level A), so the policy is
conservative and fixed here rather than per kernel:

- nopython mode only (``njit``; Numba has no silent object-mode fallback);
- ``fastmath=False``: IEEE semantics, no reassociation, no FMA contraction;
- no ``parallel``/``prange``, no Numba RNG: random draws are generated by the named
  Python streams and passed in;
- ``cache=True``: compiled code is reused across processes (ensemble workers) from
  ``__pycache__``;
- ``error_model="python"``: a division by zero raises, as the Python reference would.

Reductions are written as the reference computes them: a running ``+=`` where the
reference loops, :func:`python_sum` where it called the builtin ``sum()`` (compensated
since Python 3.12, see :mod:`madexplorer.core.exactsum`), and :func:`numpy_sum` where it
called ``ndarray.sum()`` (pairwise).

``MADEXPLORER_JIT=0`` in the environment runs the same kernels as plain Python (debugging,
coverage); results are identical by construction, only slower.
"""

import math
import os
from collections.abc import Callable
from typing import Any, cast

import numpy as np

ENABLED = os.environ.get("MADEXPLORER_JIT", "1") != "0"


def kernel[F: Callable[..., Any]](function: F) -> F:
    """Compile ``function`` under the engine's exactness policy (see module docstring)."""
    if not ENABLED:
        return function
    from numba import njit

    return cast(F, njit(cache=True, fastmath=False, error_model="python")(function))


@kernel
def _pairwise_block(values: np.ndarray, start: int, n: int) -> float:
    """numpy's pairwise-sum leaf for ``n <= 128`` elements."""
    if n < 8:
        res = 0.0
        for i in range(start, start + n):
            res += values[i]
        return res
    r0 = values[start]
    r1 = values[start + 1]
    r2 = values[start + 2]
    r3 = values[start + 3]
    r4 = values[start + 4]
    r5 = values[start + 5]
    r6 = values[start + 6]
    r7 = values[start + 7]
    i = 8
    stop = n - (n % 8)
    while i < stop:
        j = start + i
        r0 += values[j]
        r1 += values[j + 1]
        r2 += values[j + 2]
        r3 += values[j + 3]
        r4 += values[j + 4]
        r5 += values[j + 5]
        r6 += values[j + 6]
        r7 += values[j + 7]
        i += 8
    res = ((r0 + r1) + (r2 + r3)) + ((r4 + r5) + (r6 + r7))
    while i < n:
        res += values[start + i]
        i += 1
    return float(res)


@kernel
def pairwise_sum(values: np.ndarray, start: int, n: int) -> float:
    """numpy's pairwise summation of ``values[start:start + n]`` (float64, contiguous).

    The algorithm of numpy's ``DOUBLE_pairwise_sum``: below 8 elements a sequential sum
    from 0.0; up to 128, eight interleaved accumulators combined as a tree, then the
    remainder; above, ``sum(left) + sum(right)`` split at an 8-aligned half. Bit-identical
    to ``ndarray.sum()`` on contiguous float64 data (tested against numpy for many lengths).

    The split is evaluated with an explicit stack, not recursion: Numba's on-disk cache
    is unreliable for self-recursive functions linked into other cached kernels (a warm
    cache crashed the process).
    """
    if n <= 128:
        return _pairwise_block(values, start, n)
    depth = 128  # two frames per halving: ample for any int64 length
    frame_start = np.empty(depth, dtype=np.int64)
    frame_n = np.empty(depth, dtype=np.int64)
    frame_phase = np.zeros(depth, dtype=np.int64)
    results = np.empty(depth)
    top = 0
    frame_start[0], frame_n[0], frame_phase[0] = start, n, 0
    frames = 1
    while frames > 0:
        k = frames - 1
        s, m = frame_start[k], frame_n[k]
        if m <= 128:
            results[top] = _pairwise_block(values, s, m)
            top += 1
            frames -= 1
            continue
        half = m // 2
        half -= half % 8
        if frame_phase[k] == 0:  # evaluate the left half
            frame_phase[k] = 1
            frame_start[frames], frame_n[frames], frame_phase[frames] = s, half, 0
            frames += 1
        elif frame_phase[k] == 1:  # then the right half
            frame_phase[k] = 2
            frame_start[frames], frame_n[frames], frame_phase[frames] = s + half, m - half, 0
            frames += 1
        else:  # combine: left + right
            right = results[top - 1]
            left = results[top - 2]
            top -= 2
            results[top] = left + right
            top += 1
            frames -= 1
    return float(results[0])


@kernel
def numpy_sum(values: np.ndarray, start: int, n: int) -> float:
    """``values[start:start + n].sum()`` exactly as numpy computes it (zero-initialized)."""
    return 0.0 + pairwise_sum(values, start, n)


@kernel
def python_sum(values: np.ndarray, start: int, n: int) -> float:
    """``sum(values[start:start + n].tolist())`` with CPython's float semantics (>= 3.12).

    The builtin starts from the integer 0 (so the first term's -0.0 becomes 0.0), then
    accumulates the remaining terms with Neumaier compensation and adds the compensation
    at the end when it is nonzero and finite (``Python/bltinmodule.c``). For two terms
    this equals ``0.0 + a + b``; for more it generally does not.
    """
    if n == 0:
        return 0.0
    total = 0.0 + values[start]
    compensation = 0.0
    for i in range(start + 1, start + n):
        x = values[i]
        t = total + x
        if abs(total) >= abs(x):
            compensation += (total - t) + x
        else:
            compensation += (x - t) + total
        total = t
    if compensation != 0.0 and math.isfinite(compensation):
        total += compensation
    return float(total)
